version: '3'

services:
  bookservice:
    build: ./service1
    ports:
      - "5001:5001"
    depends_on:
      - reviewservice

  reviewservice:
    build: ./service2
    ports:
      - "5002:5002"
